// CI stage 5 — RFC 8785 vector suite on Node (08-stack-and-repo §5.6, §5.4).
// The identical assertions run on Hermes in stage 6 via the standalone vector runner
// (scripts/hermes-vectors/); together they are SEC-OPLOG-06.
//
// Test titles embed "SEC-OPLOG-06" verbatim because the SEC-META-01 gate matches test
// TITLES, not file contents (security-guide §2.1.3).
//
// These vectors are transcribed from the RFC, never produced by our own canonicalizer —
// a golden file generated by the code under test would only prove the code agrees with
// itself (testing-guide T-5).
import { canonicalizeJcs, JcsInputError, utf8ToBytes, bytesToHex } from '@bolusi/core';
import {
  canonicalizationVectors,
  ieee754HexToNumber,
  numberVectors,
  propertySortingVector,
} from '@bolusi/test-support';
import { describe, expect, it } from 'vitest';

describe('SEC-OPLOG-06 — RFC 8785 JCS vectors (Node)', () => {
  describe('SEC-OPLOG-06 number serialization (RFC 8785 Appendix B)', () => {
    const serializable = numberVectors.filter((vector) => vector.expected !== null);
    const mustError = numberVectors.filter((vector) => vector.expected === null);

    // The whole reason stage 6 exists: JCS number output is ES number->string, which is
    // an engine-implemented algorithm (shortest round-tripping representation). If Hermes
    // and V8 disagreed on ANY of these, two devices would hash different preimages.
    it.each(serializable)(
      'SEC-OPLOG-06 serializes IEEE 754 $ieee754 as $expected ($comment)',
      ({ ieee754, expected }) => {
        expect(canonicalizeJcs(ieee754HexToNumber(ieee754))).toBe(expected);
      },
    );

    it.each(mustError)('SEC-OPLOG-06 rejects IEEE 754 $ieee754 ($comment)', ({ ieee754 }) => {
      const value = ieee754HexToNumber(ieee754);
      // RFC 8785: "occurrences of NaN or Infinity MUST cause a compliant JCS
      // implementation to terminate with an appropriate error."
      expect(() => canonicalizeJcs(value)).toThrow(JcsInputError);
      expect(() => canonicalizeJcs(value)).toThrow(/NON_FINITE_NUMBER/);
    });

    it('SEC-OPLOG-06 covers every RFC 8785 Appendix B row', () => {
      // Guards against a vector silently disappearing from the golden file.
      expect(numberVectors).toHaveLength(26);
      expect(mustError).toHaveLength(2);
    });
  });

  describe('SEC-OPLOG-06 canonicalization (RFC 8785 §3.2)', () => {
    it.each(canonicalizationVectors)(
      'SEC-OPLOG-06 canonicalizes $name to the RFC text',
      ({ input, expected }) => {
        expect(canonicalizeJcs(input as Parameters<typeof canonicalizeJcs>[0])).toBe(expected);
      },
    );

    it.each(canonicalizationVectors)(
      'SEC-OPLOG-06 canonicalizes $name to the exact RFC 8785 §3.2.4 UTF-8 bytes',
      ({ input, expectedUtf8Hex }) => {
        // §3.2.4 is the real contract: the hash preimage is BYTES, not a JS string.
        const bytes = utf8ToBytes(canonicalizeJcs(input as Parameters<typeof canonicalizeJcs>[0]));
        expect(bytesToHex(bytes)).toBe(expectedUtf8Hex);
      },
    );
  });

  describe('SEC-OPLOG-06 property sorting (RFC 8785 §3.2.3)', () => {
    it('SEC-OPLOG-06 sorts property names by UTF-16 code unit, not code point', () => {
      // The load-bearing case is the emoji (U+1F600): as a surrogate pair its first code
      // unit is 0xD83D, which sorts BEFORE the Hebrew 0xFB33 — while a code-POINT sort
      // (what Python and Go produce by default) puts it after. Getting this wrong yields
      // a different key order and therefore a different hash.
      const canonical = canonicalizeJcs(propertySortingVector.input);
      const valuesInOutputOrder = [...canonical.matchAll(/:"([^"]*)"/g)].map((match) => match[1]);
      expect(valuesInOutputOrder).toEqual(propertySortingVector.expectedValueOrder);
    });
  });
});
