// Catalog codegen (07-i18n §3.3, §3.4). Emits two checked-in artifacts from the catalog JSON:
//
//   src/generated/keys.ts       TranslationKey union + TranslationResources shape (from `id`,
//                               which is complete by definition, §7.1)
//   src/generated/resources.ts  the statically merged resources i18next is initialised with
//
// Why generate resources instead of importing the JSON from src/: the package is platform-free
// and builds with rootDir=src (08 §3.4), so `import '../catalogs/core/id.json'` cannot compile.
// Generating keeps the JSON files the reviewable artifact (§3.3) while the runtime stays a
// plain TS module that Hermes and Node both load with no JSON-module or fs support needed.
//
// Both files are checked in; check.mjs re-generates and diffs them, so a catalog edit without a
// regen fails CI instead of drifting.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { format, resolveConfig } from 'prettier';

import { SOURCE_LOCALE, flattenSource } from './gates.mjs';
import { CATALOG_ROOT, PACKAGE_ROOT, RESERVED_NAMESPACES, SEEDED_LOCALES } from './seed.mjs';

const GENERATED_DIR = join(PACKAGE_ROOT, 'src', 'generated');
export const KEYS_PATH = join(GENERATED_DIR, 'keys.ts');
export const RESOURCES_PATH = join(GENERATED_DIR, 'resources.ts');

const BANNER = `// AUTO-GENERATED by scripts/gen.mjs from the catalogs — do not edit by hand.
// Regenerate with \`pnpm --filter @bolusi/i18n i18n:gen\`; \`pnpm i18n:check\` fails when it is stale.`;

/**
 * Read one locale's catalogs, merged and keyed by namespace.
 * @param {string} locale
 * @returns {Record<string, unknown>}
 */
export function readMergedCatalog(locale) {
  /** @type {Record<string, unknown>} */
  const merged = {};
  for (const namespace of RESERVED_NAMESPACES) {
    merged[namespace] = JSON.parse(
      readFileSync(join(CATALOG_ROOT, namespace, `${locale}.json`), 'utf8'),
    );
  }
  return merged;
}

/**
 * @param {Record<string, unknown>} tree
 * @returns {string[]} fully-qualified keys, sorted
 */
function keysOf(tree) {
  /** @type {string[]} */
  const keys = [];
  for (const [namespace, subtree] of Object.entries(tree)) {
    for (const { key } of flattenSource({
      id: namespace,
      namespace,
      locale: SOURCE_LOCALE,
      tree: /** @type {Record<string, unknown>} */ (subtree),
    })) {
      keys.push(key);
    }
  }
  return keys.sort();
}

/** Leaf emitter for the type side — identifies the interface pass in emitObject. */
const EMIT_STRING = () => 'string';

/**
 * @param {Record<string, unknown>} node
 * @param {number} depth
 * @param {(value: string) => string} leaf
 * @param {string} terminator
 * @returns {string}
 */
function emitObject(node, depth, leaf, terminator) {
  const pad = '  '.repeat(depth);
  const lines = [];
  for (const [segment, value] of Object.entries(node)) {
    if (value !== null && typeof value === 'object') {
      const body = emitObject(
        /** @type {Record<string, unknown>} */ (value),
        depth + 1,
        leaf,
        terminator,
      );
      if (body === '') {
        // A namespace with no rows yet — `permission` is skeleton-only until the labels land
        // with their registry PRs (ui-labels.md).
        //
        // `Record<never, never>` and not `Record<string, never>`: the latter carries an index
        // signature, so `keyof` is `string` and i18next's key-path derivation recurses on
        // `${string}.${string}...` until tsc gives up with TS2589. `Record<never, never>` has
        // `keyof = never` — the same "no keys here" that a bare `{}` means, without tripping
        // @typescript-eslint/no-empty-object-type ("{} allows any non-nullish value").
        lines.push(
          `${pad}'${segment}': ${leaf === EMIT_STRING ? 'Record<never, never>' : '{}'}${terminator}`,
        );
        continue;
      }
      lines.push(`${pad}'${segment}': {`);
      lines.push(body);
      lines.push(`${pad}}${terminator}`);
    } else {
      lines.push(`${pad}'${segment}': ${leaf(String(value))}${terminator}`);
    }
  }
  return lines.join('\n');
}

/**
 * @param {Record<string, unknown>} sourceTree the merged `id` catalog
 * @returns {string}
 */
export function renderKeys(sourceTree) {
  const keys = keysOf(sourceTree);
  const union = keys.length === 0 ? '  never' : keys.map((key) => `  | '${key}'`).join('\n');
  return `${BANNER}
// Key grammar and the derived-key exceptions are owned by ai-docs/07-i18n.md §3.1.

/** Every label key in the catalog (07-i18n §3.4). */
export type TranslationKey =
${union};

/** Nested shape of the merged catalog; fed to i18next's CustomTypeOptions in src/types.ts. */
export interface TranslationResources {
${emitObject(sourceTree, 1, EMIT_STRING, ';')}
}
`;
}

/**
 * @param {Record<string, Record<string, unknown>>} byLocale
 * @returns {string}
 */
export function renderResources(byLocale) {
  const blocks = Object.entries(byLocale)
    .map(
      ([locale, tree]) => `  '${locale}': {
    translation: {
${emitObject(tree, 3, (value) => JSON.stringify(value), ',')}
    },
  },`,
    )
    .join('\n');

  return `${BANNER}
// The statically merged catalogs (07-i18n §3.3): one default namespace, the namespace segment
// re-added here at merge time. Bundled with the app — never fetched.
import type { TranslationResources } from './keys.js';

/** Locales with catalog files. \`zh\` is scaffold-only (07-i18n §1) and has none. */
export type SeededLocale = ${SEEDED_LOCALES.map((locale) => `'${locale}'`).join(' | ')};

/**
 * Typing every locale against the \`id\`-derived shape makes id/en parity a compile error as
 * well as a gate failure (07-i18n §7.1.2).
 */
export type SeededResources = Record<SeededLocale, { translation: TranslationResources }>;

export const resources: SeededResources = {
${blocks}
};
`;
}

/**
 * Emitted source is run through Prettier so the generator's output is byte-identical to what
 * the pre-commit hook would write. Without this, `prettier --write` on commit would reformat
 * the file and the staleness gate in check.mjs would then fail against a clean tree.
 * @param {string} source
 * @param {string} filepath
 * @returns {Promise<string>}
 */
async function formatted(source, filepath) {
  const config = await resolveConfig(filepath);
  return format(source, { ...config, filepath });
}

/** @returns {Promise<{ keys: string, resources: string }>} */
export async function renderAll() {
  const sourceTree = readMergedCatalog(SOURCE_LOCALE);
  /** @type {Record<string, Record<string, unknown>>} */
  const byLocale = {};
  for (const locale of SEEDED_LOCALES) byLocale[locale] = readMergedCatalog(locale);
  return {
    keys: await formatted(renderKeys(sourceTree), KEYS_PATH),
    resources: await formatted(renderResources(byLocale), RESOURCES_PATH),
  };
}

async function main() {
  const rendered = await renderAll();
  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(KEYS_PATH, rendered.keys);
  writeFileSync(RESOURCES_PATH, rendered.resources);
  console.log('i18n:gen: wrote src/generated/keys.ts and src/generated/resources.ts');
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  await main();
}
