// Config plugin: inject the on-device harness entry activity (task 27a/175 deliverable #1).
//
// `apps/mobile/android/` is generated by `expo prebuild` and is git-ignored, so the ONLY way to make
// the generated `AndroidManifest.xml` declare a component — and drop a Kotlin file beside the generated
// `MainActivity.kt` — is a config plugin. This one:
//   1. writes `HarnessActivity.kt` into the app package via a dangerous mod (a real ReactActivity that
//      renders the `BolusiHarness` JS root and forwards the driver's `--es bolusiHarnessRunId` intent
//      extra to JS as initialProps), and
//   2. registers `<activity android:name=".HarnessActivity" android:exported="true">` in the manifest.
//
// LOADING: referenced from `app.config.ts`'s `plugins` array by STRING PATH ('./plugins/withHarnessActivity'),
// NOT a nested import — Expo's plugin resolver transpiles a `.ts` plugin (pluginExtensions includes `.ts`),
// but Expo's CONFIG loader does NOT transpile a nested `.ts` import from app.config.ts. For the same
// reason this file has NO relative `.ts` imports: the wire literals (component name, run-id extra) are
// duplicated from `src/harness/contract.ts` and pinned equal by test/harness-activity-plugin.test.ts,
// rather than imported across the build/runtime boundary.
//
// The driver (`scripts/harness-device.mjs`) launches EXACTLY `com.bolusi.app/com.bolusi.app.HarnessActivity`
// with `-n` (explicit component), so no intent-filter is needed — only `exported="true"` so `adb`/`am`
// may start it. NAMING TRAP (task 175 trap 2): the activity name must NOT contain "Exception", because
// `amStartFailureReason`'s unanchored `/Exception/` matches `am start`'s echoed component name and would
// self-trip. `HarnessActivity` is safe.
//
// FLAG-GATED AT PREBUILD. The activity is injected ONLY when `EXPO_PUBLIC_BOLUSI_TEST_HARNESS=1` (the
// env the CI `test`-profile assemble sets). So an exported activity — a launch surface — never lands in
// a production or preview manifest: no flag → no `HarnessActivity.kt`, no manifest entry. Falsified both
// ways by prebuild + manifest grep (task 175 acceptance).
import { promises as fs } from 'node:fs';
import path from 'node:path';

import {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  type ConfigPlugin,
} from 'expo/config-plugins';

/** The Android class / manifest `android:name` (relative, so it resolves to `<package>.HarnessActivity`). */
export const HARNESS_ACTIVITY_NAME = 'HarnessActivity';

/** The `AppRegistry` key HarnessActivity renders — MUST equal `contract.ts:HARNESS_COMPONENT_NAME`
 * (asserted in test/harness-activity-plugin.test.ts, since this build-time file cannot import the
 * runtime `.ts`). A drift boots the activity to a blank screen (no component). */
export const HARNESS_COMPONENT_NAME = 'BolusiHarness';

/** The intent-extra key the driver passes the run id under — MUST equal `contract.ts:HARNESS_RUN_ID_EXTRA`
 * and `scripts/harness-device.mjs`'s `--es` key (asserted in the same test). */
export const HARNESS_RUN_ID_EXTRA = 'bolusiHarnessRunId';

/** True only when the harness flag is set at prebuild time — mirrors `harnessEnabled()` at build time. */
export function harnessBuildEnabled(): boolean {
  return process.env['EXPO_PUBLIC_BOLUSI_TEST_HARNESS'] === '1';
}

/**
 * The `HarnessActivity.kt` source. Mirrors the prebuild-generated `MainActivity.kt` (New Architecture:
 * `ReactActivityDelegateWrapper` + `DefaultReactActivityDelegate`, `BuildConfig.IS_NEW_ARCHITECTURE_ENABLED`)
 * and changes exactly two things: `getMainComponentName()` returns the `BolusiHarness` JS key, and the
 * delegate's `getLaunchOptions()` returns the launching intent's extras so `--es ${HARNESS_RUN_ID_EXTRA}`
 * reaches the JS root as initialProps.
 */
export function harnessActivityKotlin(pkg: string): string {
  return `package ${pkg}

import android.os.Bundle

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

import expo.modules.ReactActivityDelegateWrapper

// The on-device harness entry (task 27a/175). Launched by scripts/harness-device.mjs as
// \`com.bolusi.app/.${HARNESS_ACTIVITY_NAME}\`. It renders the "${HARNESS_COMPONENT_NAME}" JS root
// (registered flag-gated in src/harness/register.ts), which runs the required gates and emits the one
// tagged result. Injected ONLY into test-profile builds (see withHarnessActivity).
class ${HARNESS_ACTIVITY_NAME} : ReactActivity() {
  override fun getMainComponentName(): String = "${HARNESS_COMPONENT_NAME}"

  override fun createReactActivityDelegate(): ReactActivityDelegate {
    // Forward the launching intent's extras (the driver's --es ${HARNESS_RUN_ID_EXTRA} <id>) to JS as
    // initialProps, so the harness echoes the run id back for the driver's freshness check.
    val launchExtras = intent?.extras
    return ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(
        this,
        mainComponentName,
        fabricEnabled
      ) {
        override fun getLaunchOptions(): Bundle? = launchExtras
      }
    )
  }
}
`;
}

/**
 * Add `<activity android:name=".HarnessActivity" …>` to `<application>`, idempotently. Pure so it is
 * unit-testable against a fake manifest (test/harness-activity-plugin.test.ts). Exported + no
 * intent-filter: the driver launches it by explicit component, and it must never be a launcher entry.
 */
export function addHarnessActivityToManifest(
  androidManifest: AndroidConfig.Manifest.AndroidManifest,
): AndroidConfig.Manifest.AndroidManifest {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.activity = application.activity ?? [];
  const name = `.${HARNESS_ACTIVITY_NAME}`;
  const already = application.activity.some((activity) => activity.$['android:name'] === name);
  if (!already) {
    application.activity.push({
      $: {
        'android:name': name,
        'android:exported': 'true',
        'android:theme': '@style/AppTheme',
        'android:configChanges':
          'keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode|smallestScreenSize',
      },
    });
  }
  return androidManifest;
}

const withHarnessActivity: ConfigPlugin = (config) => {
  if (!harnessBuildEnabled()) return config;

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const pkg = config.android?.package ?? 'com.bolusi.app';
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...pkg.split('.'),
      );
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(
        path.join(dir, `${HARNESS_ACTIVITY_NAME}.kt`),
        harnessActivityKotlin(pkg),
        'utf8',
      );
      return config;
    },
  ]);

  config = withAndroidManifest(config, (config) => {
    config.modResults = addHarnessActivityToManifest(config.modResults);
    return config;
  });

  return config;
};

export default withHarnessActivity;
