// Config plugin: inject the on-device harness entry activity (task 27a/175 deliverable #1).
//
// `apps/mobile/android/` is generated by `expo prebuild` and is git-ignored, so the ONLY way to make
// the generated `AndroidManifest.xml` declare a component — and drop a Kotlin file beside the generated
// `MainActivity.kt` — is a config plugin. This one:
//   1. writes `HarnessActivity.kt` into the app package via a dangerous mod (a real ReactActivity that
//      renders the `BolusiHarness` JS root and forwards the driver's `--es bolusiHarnessRunId` intent
//      extra to JS as initialProps), and
//   2. registers `<activity android:name=".HarnessActivity" android:exported="true">` in the manifest.
//
// LOADING: referenced from `app.config.ts`'s `plugins` array by STRING PATH ('./plugins/withHarnessActivity'),
// NOT a nested import — Expo's plugin resolver transpiles a `.ts` plugin (pluginExtensions includes `.ts`),
// but Expo's CONFIG loader does NOT transpile a nested `.ts` import from app.config.ts. For the same
// reason this file has NO relative `.ts` imports: the wire literals (component name, run-id extra) are
// duplicated from `src/harness/contract.ts` and pinned equal by test/harness-activity-plugin.test.ts,
// rather than imported across the build/runtime boundary.
//
// The driver (`scripts/harness-device.mjs`) launches EXACTLY `com.bolusi.app/com.bolusi.app.HarnessActivity`
// with `-n` (explicit component), so no intent-filter is needed — only `exported="true"` so `adb`/`am`
// may start it. NAMING TRAP (task 175 trap 2): the activity name must NOT contain "Exception", because
// `amStartFailureReason`'s unanchored `/Exception/` matches `am start`'s echoed component name and would
// self-trip. `HarnessActivity` is safe.
//
// FLAG-GATED AT PREBUILD. The activity is injected ONLY when `EXPO_PUBLIC_BOLUSI_TEST_HARNESS=1` (the
// env the CI `test`-profile assemble sets). So an exported activity — a launch surface — never lands in
// a production or preview manifest: no flag → no `HarnessActivity.kt`, no manifest entry. Falsified both
// ways by prebuild + manifest grep (task 175 acceptance).
import { promises as fs } from 'node:fs';
import path from 'node:path';

import {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  type ConfigPlugin,
} from 'expo/config-plugins';

/** The Android class / manifest `android:name` (relative, so it resolves to `<package>.HarnessActivity`). */
export const HARNESS_ACTIVITY_NAME = 'HarnessActivity';

/** The `AppRegistry` key HarnessActivity renders — MUST equal `contract.ts:HARNESS_COMPONENT_NAME`
 * (asserted in test/harness-activity-plugin.test.ts, since this build-time file cannot import the
 * runtime `.ts`). A drift boots the activity to a blank screen (no component). */
export const HARNESS_COMPONENT_NAME = 'BolusiHarness';

/** The intent-extra key the driver passes the run id under — MUST equal `contract.ts:HARNESS_RUN_ID_EXTRA`
 * and `scripts/harness-device.mjs`'s `--es` key (asserted in the same test). */
export const HARNESS_RUN_ID_EXTRA = 'bolusiHarnessRunId';

/** True only when the harness flag is set at prebuild time — mirrors `harnessEnabled()` at build time. */
export function harnessBuildEnabled(): boolean {
  return process.env['EXPO_PUBLIC_BOLUSI_TEST_HARNESS'] === '1';
}

/**
 * The ONLY hosts the harness build may reach over cleartext (HTTP). Both are local test endpoints, never
 * a real server: `127.0.0.1` is the loopback the CHAOS-03/06/07 net handoff reaches the host `@bolusi/server`
 * on via `adb reverse` (the driver's per-scenario baseUrls), and `10.0.2.2` is the emulator's alias for the
 * host loopback that `EXPO_PUBLIC_API_URL` (`http://10.0.2.2:3000`) points the normal sync client at. The
 * single source for both the generated XML and the plugin test — a drift here silently re-bricks the round trip.
 */
export const HARNESS_CLEARTEXT_HOSTS = ['127.0.0.1', '10.0.2.2'] as const;

/** The `res/xml/<name>.xml` resource the harness manifest points `android:networkSecurityConfig` at. */
export const HARNESS_NETWORK_SECURITY_CONFIG_RESOURCE = 'network_security_config';

/**
 * The `HarnessActivity.kt` source. Mirrors the prebuild-generated `MainActivity.kt` (New Architecture:
 * `ReactActivityDelegateWrapper` + `DefaultReactActivityDelegate`, `BuildConfig.IS_NEW_ARCHITECTURE_ENABLED`)
 * and changes exactly two things: `getMainComponentName()` returns the `BolusiHarness` JS key, and the
 * delegate's `getLaunchOptions()` returns the launching intent's extras so `--es ${HARNESS_RUN_ID_EXTRA}`
 * reaches the JS root as initialProps.
 */
export function harnessActivityKotlin(pkg: string): string {
  return `package ${pkg}

import android.os.Bundle

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

import expo.modules.ReactActivityDelegateWrapper

// The on-device harness entry (task 27a/175). Launched by scripts/harness-device.mjs as
// \`com.bolusi.app/.${HARNESS_ACTIVITY_NAME}\`. It renders the "${HARNESS_COMPONENT_NAME}" JS root
// (registered flag-gated in src/harness/register.ts), which runs the required gates and emits the one
// tagged result. Injected ONLY into test-profile builds (see withHarnessActivity).
class ${HARNESS_ACTIVITY_NAME} : ReactActivity() {
  override fun getMainComponentName(): String = "${HARNESS_COMPONENT_NAME}"

  override fun createReactActivityDelegate(): ReactActivityDelegate {
    return ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(
        this,
        mainComponentName,
        fabricEnabled
      ) {
        // Forward the launching intent's extras (the driver's --es ${HARNESS_RUN_ID_EXTRA} <id>) to JS
        // as initialProps, so the harness echoes the run id back for the driver's freshness check.
        //
        // READ LAZILY, NOT CAPTURED (task 177 runId fix). ReactActivity's CONSTRUCTOR calls
        // createReactActivityDelegate() (ReactActivity.java: \`protected ReactActivity() { mDelegate =
        // createReactActivityDelegate(); }\`), and at construction time the Activity is NOT yet attached
        // to its launching intent, so getIntent() is null. The previous code snapshotted the extras into
        // a local at delegate-construction and froze that null — the driver's --es ${HARNESS_RUN_ID_EXTRA}
        // never reached JS and the emitted result carried an empty run id (the task 175 hardware run,
        // run 30147394950). RN calls getLaunchOptions() from ReactActivityDelegate.onCreate()
        // (composeLaunchOptions()), AFTER the intent is attached, so reading intent?.extras HERE returns
        // the real launching extras.
        override fun getLaunchOptions(): Bundle? = this@${HARNESS_ACTIVITY_NAME}.intent?.extras
      }
    )
  }
}
`;
}

/**
 * Add `<activity android:name=".HarnessActivity" …>` to `<application>`, idempotently. Pure so it is
 * unit-testable against a fake manifest (test/harness-activity-plugin.test.ts). Exported + no
 * intent-filter: the driver launches it by explicit component, and it must never be a launcher entry.
 */
export function addHarnessActivityToManifest(
  androidManifest: AndroidConfig.Manifest.AndroidManifest,
): AndroidConfig.Manifest.AndroidManifest {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.activity = application.activity ?? [];
  const name = `.${HARNESS_ACTIVITY_NAME}`;
  const already = application.activity.some((activity) => activity.$['android:name'] === name);
  if (!already) {
    application.activity.push({
      $: {
        'android:name': name,
        'android:exported': 'true',
        'android:theme': '@style/AppTheme',
        'android:configChanges':
          'keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode|smallestScreenSize',
      },
    });
  }
  return androidManifest;
}

/**
 * The `res/xml/network_security_config.xml` body for the harness build. Permits cleartext ONLY to the
 * local test hosts (HARNESS_CLEARTEXT_HOSTS); every other domain falls through to the platform default
 * `base-config`, which since API 28 is `cleartextTrafficPermitted="false"` — so this does NOT open the app
 * to cleartext generally, it carves out exactly the loopback + emulator-host test endpoints. Needed because
 * an Android release build blocks cleartext by default, so the on-device CHAOS runners' `fetch` to
 * `http://127.0.0.1:<port>` threw `UnknownServiceException: CLEARTEXT communication … not permitted` and
 * every net gate crashed before a verdict (emulator run 34026908808). Pure so the exact host set is
 * unit-asserted (test/harness-activity-plugin.test.ts). Injected ONLY into the flag-gated harness build.
 */
export function harnessNetworkSecurityConfigXml(): string {
  const domains = HARNESS_CLEARTEXT_HOSTS.map(
    (host) => `    <domain includeSubdomains="false">${host}</domain>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Harness build only (EXPO_PUBLIC_BOLUSI_TEST_HARNESS=1). Cleartext is permitted ONLY to the local
     test hosts below; all other domains inherit the platform default base-config (cleartext DENIED on
     API 28+). Never injected into a production/preview build — see withHarnessActivity. -->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
${domains}
  </domain-config>
</network-security-config>
`;
}

/**
 * Point `<application android:networkSecurityConfig>` at the harness `@xml/network_security_config` resource,
 * idempotently. Pure so it is unit-testable against a fake manifest. A sibling of the backup attributes
 * expo-secure-store sets on the same `<application>` (app.config.ts) — different attribute, no interaction.
 */
export function setHarnessNetworkSecurityConfig(
  androidManifest: AndroidConfig.Manifest.AndroidManifest,
): AndroidConfig.Manifest.AndroidManifest {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.$['android:networkSecurityConfig'] =
    `@xml/${HARNESS_NETWORK_SECURITY_CONFIG_RESOURCE}`;
  return androidManifest;
}

const withHarnessActivity: ConfigPlugin = (config) => {
  if (!harnessBuildEnabled()) return config;

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const pkg = config.android?.package ?? 'com.bolusi.app';
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...pkg.split('.'),
      );
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(
        path.join(dir, `${HARNESS_ACTIVITY_NAME}.kt`),
        harnessActivityKotlin(pkg),
        'utf8',
      );
      return config;
    },
  ]);

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const xmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      await fs.mkdir(xmlDir, { recursive: true });
      await fs.writeFile(
        path.join(xmlDir, `${HARNESS_NETWORK_SECURITY_CONFIG_RESOURCE}.xml`),
        harnessNetworkSecurityConfigXml(),
        'utf8',
      );
      return config;
    },
  ]);

  config = withAndroidManifest(config, (config) => {
    config.modResults = addHarnessActivityToManifest(config.modResults);
    config.modResults = setHarnessNetworkSecurityConfig(config.modResults);
    return config;
  });

  return config;
};

export default withHarnessActivity;
